tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

brew "nvm"
brew "git"
brew "yarn"

# Apps
cask "visual-studio-code"
cask "1password"
cask "1password-cli"
cask "firefox"
cask "google-chrome"
cask "hyper"
cask "spotify"
cask "alfred"
cask "dash"
cask "font-fira-code"
